version: '3'
services:
    postgres:
        image: postgres:14
        env_file:
            - .env
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "airflow"]
            interval: 5s
            retries: 5
        restart: always
        networks:
            - dynamic_dag

    scheduler:
        build: .
        command: scheduler
        restart: on-failure
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
            - ./data:/opt/airflow/data
            - ~/.google/:/.google/
        networks:
            - dynamic_dag

    webserver:
        build: .
        command: webserver
        entrypoint: ./scripts/entrypoint.sh
        restart: on-failure
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ~/.google/:/.google/:ro
            - ./scripts:/opt/airflow/scripts
            - ./data:/opt/airflow/data
        ports:
            - "8080:8080"
        healthcheck:
            test: [ "CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]" ]
            interval: 30s
            timeout: 30s
            retries: 3
        networks:
            - dynamic_dag

volumes:
    postgres-db-volume:

networks:
    dynamic_dag:
        external: true